// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjm7x03rsCLrflwpn-Hknr0pmJIkp0P4',
    appId: '1:501717809756:web:fea2fcc8701c62d57d8499',
    messagingSenderId: '501717809756',
    projectId: 'chat-app-demo-ed407',
    authDomain: 'chat-app-demo-ed407.firebaseapp.com',
    storageBucket: 'chat-app-demo-ed407.firebasestorage.app',
    measurementId: 'G-HVFGC0SYLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERkHGQeVTC7R4CzpcRj7yFHgM-u3MAHs',
    appId: '1:501717809756:android:5f4cb2733537a0dc7d8499',
    messagingSenderId: '501717809756',
    projectId: 'chat-app-demo-ed407',
    storageBucket: 'chat-app-demo-ed407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbOXu_1lblB6dIQvNk0D9mDw3hGfzM2U',
    appId: '1:501717809756:ios:ddfdb3f7d0fc34e87d8499',
    messagingSenderId: '501717809756',
    projectId: 'chat-app-demo-ed407',
    storageBucket: 'chat-app-demo-ed407.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbOXu_1lblB6dIQvNk0D9mDw3hGfzM2U',
    appId: '1:501717809756:ios:ddfdb3f7d0fc34e87d8499',
    messagingSenderId: '501717809756',
    projectId: 'chat-app-demo-ed407',
    storageBucket: 'chat-app-demo-ed407.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjm7x03rsCLrflwpn-Hknr0pmJIkp0P4',
    appId: '1:501717809756:web:7e900b3cfcb9cfe47d8499',
    messagingSenderId: '501717809756',
    projectId: 'chat-app-demo-ed407',
    authDomain: 'chat-app-demo-ed407.firebaseapp.com',
    storageBucket: 'chat-app-demo-ed407.firebasestorage.app',
    measurementId: 'G-FY5TQ66T59',
  );
}
